# Generated by Django 3.2.4 on 2021-06-25 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_course_isonetoone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='course_id',
        ),
    ]
