# Generated by Django 3.2.4 on 2021-06-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_skill_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.FileField(null=True, upload_to='', verbose_name=''),
        ),
    ]
